[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[env]
  [env.production]
    ATTENDANCE_PASSWORD = "77077707"

[[redirects]]
  from = "/.netlify/functions/:name"
  to = "/.netlify/functions/:name"
  status = 200
